project:
  type: website

website:
  title: "Massachusetts Tax Overrides and Govt Finances"
  navbar:
    left:
      - text: "Override Data"
        href: override_data_analysis.qmd
      - text: "Debt Data"
        href: Debt_data_analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left



