---
title: "Summary of Massachusetts Tax Override Data"
author: Gang Chen
Email: gchen3@albany.edu
date: "`r format(Sys.Date(), '%B %d, %Y')`"
format: 
  html:
    toc: true
    
---

## Main data sources

1.  DLS Gateway, governance data https://dlsgateway.dor.state.ma.us/gateway/DLSPublic/Search/Search
2.  Mass databank https://www.mass.gov/info-details/division-of-local-services-municipal-databank
3.  DLS proposition 2 1/2 override and underride votes https://dlsgateway.dor.state.ma.us/reports/rdPage.aspx?rdReport=Votes.Prop2_5.OverrideUnderride
4.  Mass municipal data hub https://www.mma.org/#data-hub

<!-- Input data -->

```{r data}
#| echo: false
#| include: false

library(tidyverse)
library(foreign)
library(readxl)
library(here)
library(gt)

filepath <- getwd()
setwd("C:/Users/Gang Chen/OneDrive - University at Albany - SUNY/r-projects/mass-override")

override <- read_excel(here::here("data", "override.xlsx")) |>
  mutate(taxoverride = 1)
head(override)

debt_ex <- read_excel(here::here("data", "debt_exclusion.xlsx")) |>
  mutate(debtexclusion = 1)
head(debt_ex)

capital_ex <- read_excel(here::here("data", "capital_exclusion.xlsx")) |>
  mutate(capitalexclusion = 1)
head(capital_ex)

stable_ex <- read_excel(here::here("data", "stable_exclusion.xlsx")) |>
  mutate(stableexclusion = 1)
head(stable_ex)

ratings_moody <- read.csv(here::here("data", "bondratings_moody.csv"))
head(ratings_moody)

ratings_sp <- read.csv(here::here("data", "bondratings_sp.csv"))
head(ratings_sp)

```

<!-- Merge and clean data -->

```{r}
#| echo: false
#| include: false

override_all <- override |>
  bind_rows(capital_ex, debt_ex, stable_ex) 

names(override_all) <- tolower(names(override_all))
names(override_all) <- gsub(" |/|_", "", names(override_all))

names(override_all) 

override_all_clean <- override_all |> 
  arrange(municipality, fiscalyear, votetype) |> 
  mutate(across(c(yesvotes, novotes, amount), ~ gsub(",", "", .))) |> #get rid of the comma
  mutate(yesvotes = case_when (
    is.na(yesvotes) ~ as.numeric(numberyes),
    TRUE ~ as.numeric(yesvotes)),
    
    novotes = case_when (
    is.na(novotes) ~ as.numeric(numberno),
    TRUE ~ as.numeric(novotes)),
    
    votetype = case_when (
    debtexclusion == 1 ~ "Debt",
    capitalexclusion == 1 ~ "Capital",
    stableexclusion == 1 ~ "Stablization",
    TRUE ~ "Tax Override")
    ) |>
  select(-numberyes, -numberno)  |>
  mutate(per_yes = yesvotes/(yesvotes+novotes)) |>
  mutate(winloss_code = case_when (
    winloss == "WIN" ~ 1,
    TRUE ~ 0))

saveRDS(override_all_clean, here::here("data", "override_all_clean.RData"))
  
override_sum <-
  override_all_clean |> 
  group_by(municipality, votetype) |> 
  summarize(average_yes_percent = mean(per_yes, na.rm = TRUE), 
            average_win = mean(winloss_code, na.rm = TRUE),
            count = n(), .groups = 'drop')

override_sum_abtowns <- override_sum |> filter(municipality == "Acton")

override_sum_type <- override_sum |> 
  group_by(votetype) |> 
  summarize(average_yes_percent = mean(average_yes_percent, na.rm = TRUE), 
            average_win = mean(average_win, na.rm = TRUE),
            count = n())

override_sum_year <- override_all_clean |> 
  group_by(fiscalyear) |> 
  summarize(average_yes_percent = mean(per_yes, na.rm = TRUE), 
            average_win = mean(winloss_code, na.rm = TRUE),
            count = n(), .groups = 'drop')

override_acton <- override_all_clean |> 
  filter(municipality == "Acton")  |>
  select(municipality, fiscalyear, winloss, per_yes, votetype, department, description)
```

## Summarize data

```{r}
#| echo: false
#| include: true
 
override_sum_type |> 
  gt() |>
  tab_header(
    title = md("**Overrides by type**")
  ) |>
  tab_source_note(
    source_note = "Source: Department of Local Services proposition 2 1/2 override votes."
  ) |>
  cols_label(
    votetype = md("Type"),
    average_yes_percent = md("Percent Yes"),
    average_win = md("Percent Win"),
    count = md("Overrides (n)")
  ) |>
  fmt_percent(
    columns = c(average_yes_percent, average_win),
    decimals = 1
  )

override_sum_year|> 
  gt() |>
  tab_header(
    title = md("**Overrides by year **")
  ) |>
  tab_source_note(
    source_note = "Source: Department of Local Services proposition 2 1/2 override votes."
  ) |>
  cols_label(
    fiscalyear = "Year",
    average_yes_percent = md("Percent Yes"),
    average_win = md("Percent Win"),
    count = md("Overrides (n)")
  ) |>
  fmt_percent(
    columns = c(average_yes_percent, average_win),
    decimals = 1
  )

override_sum_abtowns |> 
  gt() |>
  tab_header(
    title = md("**Acton Town Overrides**")
  ) |>
  tab_source_note(
    source_note = "Source: Department of Local Services proposition 2 1/2 override votes."
  ) |>
  cols_label(
    municipality = "Town",
    votetype = md("Type"),
    average_yes_percent = md("Percent Yes"),
    average_win = md("Percent Win"),
    count = md("Overrides (n)")
  ) |>
  fmt_percent(
    columns = c(average_yes_percent, average_win),
    decimals = 1
  )

override_acton |> 
  gt() |>
  tab_header(
    title = md("**Acton Town Overrides**")
  ) |>
  tab_source_note(
    source_note = "Source: Department of Local Services proposition 2 1/2 override votes."
  ) |>
  cols_label(
    municipality = "Town", 
    fiscalyear = "Year", 
    winloss = "Result", 
    per_yes = "Percent Yes", 
    votetype = "Type", 
    department = "Department", 
    description = "Description"
  ) |>
  fmt_percent(
    columns = c(per_yes),
    decimals = 1
  )


```

## Analyzing the impact of past overrides and fails 

```{r impact_override}
#| echo: false
#| include: true
#| message: false
#| warning: false
#| results: asis

library(plm)
library(stargazer)

override_year <- override_all_clean %>%
  select(-dorcode, -votedate, -department, -description) %>%
  mutate (win_percent = yesvotes / (yesvotes + novotes))

all_munis <- unique(override_year$municipality)
all_years <- seq(min(override_year$fiscalyear), max(override_year$fiscalyear))

override_panel <- expand_grid(
  municipality = all_munis,
  fiscalyear = all_years,
)

override_fullpanel <- override_panel %>%
  left_join(override_year, by = c("municipality", "fiscalyear")) %>%
  mutate(amount = as.numeric(as.character(amount))) %>%  # Convert amount to numeric
  group_by(municipality, fiscalyear) %>%
  summarise(
    winloss    = mean(winloss_code, na.rm = TRUE),
    yesvotes   = sum(yesvotes, na.rm = TRUE),
    novotes    = sum(novotes, na.rm = TRUE),
    win_percent = mean(win_percent, na.rm = TRUE),
    amount     = sum(amount, na.rm = TRUE),
    across(
      .cols = c(taxoverride, capitalexclusion, debtexclusion, stableexclusion),
      .fns  = ~ mean(.x, na.rm = TRUE)
    ),
    across(
      c(taxoverride, capitalexclusion, debtexclusion, stableexclusion),
      ~ replace_na(.x, 0)
    ),
    .groups = "drop"
  )

override_fullpanel <- pdata.frame(
  override_fullpanel,
  index = c("municipality", "fiscalyear")
)

override_fullpanel <- override_fullpanel %>%
  mutate(
    override = case_when(
      !is.na(winloss) ~ 1,
      TRUE ~ 0
    ),
    override_loss = case_when(
      winloss == 0 ~ 1,
      TRUE ~ 0
    ),
    override_win = case_when(
      winloss == 1 ~ 1,
      TRUE ~ 0
    ),
    override_mix = case_when(
      winloss > 0 & winloss < 1 ~ 1,
      TRUE ~ 0
    ),
    override_close = case_when(
      win_percent >0.50 & win_percent < 0.55 ~ 1,
      TRUE ~ 0
    )
  )

controls <- c("taxoverride", "capitalexclusion", "debtexclusion", "stableexclusion", "amount")


# Model 1-3: using a 1-period lag
model1 <- plm(
  winloss ~ lag(override, 1), 
  data  = override_fullpanel,
  model = "within"
)


model2 <- plm(
  winloss ~ lag(override_loss, 1), 
  data  = override_fullpanel,
  model = "within"
)

model3 <- plm(
  winloss ~ lag(override_close, 1), 
  data  = override_fullpanel,
  model = "within"
)

# Model 1-3: using a 1-period lag

model4 <- plm(
  win_percent ~ lag(override, 1), 
  data  = override_fullpanel,
  model = "within"
)


model5 <- plm(
  win_percent ~ lag(override_loss, 1), 
  data  = override_fullpanel,
  model = "within"
)

model6 <- plm(
  win_percent ~ lag(override_close, 1), 
  data  = override_fullpanel,
  model = "within"
)

stargazer(
  model1,
  model2,
  model3,
  model4,
  model5,
  model6,
  column.labels = c("Model 1", "Model 2", "Model 3", "Model 4"),
  covariate.labels = c(
    "Having Override Year Before",
    "Loss Override Year Before",
    "Close (50~55%) Override Year Before"
  ),
  dep.var.labels = c("Probability of Getting Approval", "Percent of YES Votes"),
  type = "html",
  omit.stat = c("adj.rsq", "f")
)
```
